worker_processes 1;

env NETACEA_COOKIE_NAME;
env NETACEA_CAPTCHA_COOKIE_NAME;
env NETACEA_COOKIE_ATTRIBUTES;
env NETACEA_CAPTCHA_COOKIE_ATTRIBUTES;
env NETACEA_PROTECTOR_API_URL;
env NETACEA_PROTECTION_MODE;
env NETACEA_API_KEY;
env NETACEA_COOKIE_ENCRYPTION_KEY;
env NETACEA_SECRET_KEY;
env NETACEA_INGEST_ENABLED;
env NETACEA_REAL_IP_HEADER;
env NETACEA_REAL_IP_HEADER_INDEX;
env NETACEA_KINESIS_ACCESS_KEY;
env NETACEA_KINESIS_SECRET_KEY;
env NETACEA_KINESIS_STREAM_NAME;
env NETACEA_KINESIS_REGION;
env NETACEA_KINESIS_BATCH_SIZE;
env NETACEA_KINESIS_BATCH_TIMEOUT;

events {
  worker_connections 1024;
}

http {
  lua_package_path "/usr/local/share/lua/5.1/?.lua;;";
  lua_max_running_timers  2048;
  lua_max_pending_timers  4096;
  lua_socket_pool_size    1024;

  lua_need_request_body on;
  resolver 8.8.8.8 ipv6=off;
  lua_ssl_verify_depth 2;
  lua_ssl_trusted_certificate /etc/ssl/certs/ca-certificates.crt;

  init_worker_by_lua_block {
    local utils = require("netacea_utils")
    local env = utils.env
    local envEnabled = utils.envEnabled

    netacea = (require 'lua_resty_netacea'):new({
      mitigationEndpoint  = env('NETACEA_PROTECTOR_API_URL', ''),
      apiKey              = env('NETACEA_API_KEY', ''),
      cookieEncryptionKey = env('NETACEA_COOKIE_ENCRYPTION_KEY', ''),
      ingestEnabled       = envEnabled('NETACEA_INGEST_ENABLED', true),
      mitigationType      = env('NETACEA_PROTECTION_MODE', ''),
      cookieName          = env('NETACEA_COOKIE_NAME', ''),
      captchaCookieName   = env('NETACEA_CAPTCHA_COOKIE_NAME', ''),
      cookieAttributes    = env('NETACEA_COOKIE_ATTRIBUTES', ''),
      captchaCookieAttributes = env('NETACEA_CAPTCHA_COOKIE_ATTRIBUTES', ''),
      realIpHeader        = env('NETACEA_REAL_IP_HEADER', ''),
      realIpHeaderIndex   = tonumber(env('NETACEA_REAL_IP_HEADER_INDEX', '')),
      kinesisProperties   = {
        region         = env('NETACEA_KINESIS_REGION', 'eu-west-1'),
        stream_name    = env('NETACEA_KINESIS_STREAM_NAME', ''),
        aws_access_key = env('NETACEA_KINESIS_ACCESS_KEY', ''),
        aws_secret_key = env('NETACEA_KINESIS_SECRET_KEY', ''),
        batch_size     = tonumber(env('NETACEA_KINESIS_BATCH_SIZE', '')),
        batch_timeout  = tonumber(env('NETACEA_KINESIS_BATCH_TIMEOUT', '')),
      }
    })
  }

  log_by_lua_block {
    netacea:ingest()
  }
  access_by_lua_block {
    if ngx.var.uri == "/AtaVerifyCaptcha" then
      netacea:handleCaptcha()
    else
      netacea:mitigate()
    end
  }

  server {
    listen 80;
    server_name localhost;
    server_tokens off;
    location / {
      default_type text/html;
      content_by_lua 'ngx.say("<p>hello, world</p>")';
    }
  }
}
